# Default values for ssh-inlet-tunnel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

tunnel:
  user: nokey
  endpoint: localhost.run
  args:
    - '-R80:192.168.0.240:80'
  privateKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNDWkVsNVFHeWJ1eDFFdEk1eTliOWx3N1hJOTBiamdPQWlRMlIzcGMydmhGZ0FBQUpCZDJFSHRYZGhCCjdRQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQ1pFbDVRR3lidXgxRXRJNXk5YjlsdzdYSTkwYmpnT0FpUTJSM3BjMnZoRmcKQUFBRURNbmpxRlUyV1E4amo1OXRGNWgzbnBmcUNXUW9pa1J5aGpnY0czNDYrNmFwa1NYbEFiSnU3SFVTMGpuTDF2MlhEdApjajNSdU9BNENKRFpIZWx6YStFV0FBQUFEWFJsYzNSQVkya3ViRzlqWVd3PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
  publicKey: c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUprU1hsQWJKdTdIVVMwam5MMXYyWER0Y2ozUnVPQTRDSkRaSGVsemErRVcgdGVzdEBjaS5sb2NhbAo=
