apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ssh-inlet-tunnel.fullname" . }}
  labels:
    {{- include "ssh-inlet-tunnel.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ssh-inlet-tunnel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ssh-inlet-tunnel.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/bin/ssh
          args:
            {{- toYaml .Values.tunnel.args | nindent 12 }}
            {{- toYaml .Values.tunnel.moreArgs | nindent 12 }}
            - "-p {{ .Values.tunnel.sshport }}"
            - {{ .Values.tunnel.user }}@{{ .Values.tunnel.endpoint }}
          tty: false
          startupProbe:
            exec:
              command:
                - sh
                - "-c"
                - "netstat -tpn | grep ESTABLISHED.*ssh"
            initialDelaySeconds: 15
          volumeMounts:
            - name: vol0
              readOnly: true
              mountPath: /root/.ssh/
      restartPolicy: Always
      volumes:
        - secret:
            secretName: {{ include "ssh-inlet-tunnel.name" . }}
            defaultMode: 0400
          name: vol0

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
