apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ssh-inlet-tunnel.name" . }}
type: Opaque
data:
  id_rsa: >-
    {{ .Values.tunnel.privateKey }}
  id_rsa.pub: >-
    {{ .Values.tunnel.publicKey }}
